[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "sh -c 'uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000} --workers 1 --loop uvloop --http h11 --access-log --log-level ${LOG_LEVEL:-info}'"

# Railway automatically injects environment variables from dashboard
# No need to specify them here - Railway handles this automatically
